### ISSUE TITLE
[Feature Request] Search variables on multiple criterion

### ISSUE THREAD

**Issue by adunmore** [jtleider/censusdata#16]
Right now, it's only possible to search variables on a single criterion. It'd be convenient to specify multiple criteria on multiple fields. And it looks like it would be pretty quick to implement.

**Comment by adunmore** [comment]
If you're willing to change the API, it would be easy to do
```
censusdata.variable_info.search(src, year, criteria, tabletype)
```
where criteria is a `dict` of the format
```
criteria = {field: criterion, ...}
```

As an alternative that would avoid changes to the API, users could optionally specify `field` and `criterion` as paired lists, like:
```
censusdata.variable_info(src, year, field = [field1, field2,...], criterion = [criteria1, criteria2,...], tabletype)
```
Follows the current behavior when single strings are specified, iterates over the paired lists applying `criterion_n` to `field_n` when lists are specified.

I prefer something like the first, just because I think a `dict` would be more readable. But I understand that you might want to avoid API changes.

Thoughts?

**Comment by adunmore** [comment]
Implemented the first approach in [this](https://github.com/adunmore/censusdata/commit/2d4f10774e234f132cf10acc295acd2a8362ee1f) commit.

**Comment by adunmore** [comment]
Actually, for the first approach, a list of tuples with field-criterion pairs seems better, since then it's possible to specify multiple criteria on the same field. Still easy to implement. So something like this:
```
criteria = ((field1, criteria1), (field2, criteria2),...)
```

See [this commit](https://github.com/adunmore/censusdata/commit/2191ad8ac32babc5aac2299c8d53737e93fd0821) for implementation

**Comment by jtleider** [comment]
Hi,

I appreciate the suggestion to expand the search functionality. However, I'm uncomfortable with adding support specifically for multiple criteria, because I don't think it would be obvious how those are all being applied together. E.g., are they treated as "and" or "or" conditions? Instead, I did make a change in version 1.9 to allow the criterion to be a function, allowing more flexibility in exactly how matches are determined. This would, for instance, allow the user to specify multiple strings that should be present in a given field.

For independent criteria or criteria on different fields, I would suggest converting the search results to sets and using Python's built-in functionality for working with those. As a simple example:
`search1 = set(censusdata.search('acs5', 2015, 'concept', 'median gross rent'))`
`search2 = set(censusdata.search('acs5', 2015, 'label', '3 bedrooms'))`
`search1 & search2`

Thank you,
Julien
